builds:
- 
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - 386
  env:
  - CGO_ENABLED=0

archives:
- 
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'


release:
  github:
    owner: codefresh-io
    name: stevedore